// INTRO Control Centre design tokens — white interface, navy headings, teal highlights, orange primary
export const CC = {
  bg: '#F6F8FB',
  surface: '#FFFFFF',
  navy: '#16294E',
  navyDark: '#0F1D3A',
  teal: '#0FA3A3',
  tealSoft: '#E6F7F7',
  orange: '#F5822B',
  orangeDark: '#E06F14',
  text: '#1E2A3B',
  sub: '#64748B',
  border: '#E2E8F0',
  red: '#DC2626',
  redSoft: '#FEE2E2',
  blue: '#2563EB',
  blueSoft: '#DBEAFE',
  green: '#16A34A',
  greenSoft: '#DCFCE7',
  amber: '#D97706',
  amberSoft: '#FEF3C7',
};

export const STATUS_COLORS: Record<string, { bg: string; fg: string }> = {
  Approved: { bg: CC.greenSoft, fg: CC.green },
  approved: { bg: CC.greenSoft, fg: CC.green },
  active: { bg: CC.greenSoft, fg: CC.green },
  accepted: { bg: CC.greenSoft, fg: CC.green },
  operational: { bg: CC.greenSoft, fg: CC.green },
  Pending: { bg: CC.amberSoft, fg: CC.amber },
  pending: { bg: CC.amberSoft, fg: CC.amber },
  new: { bg: CC.blueSoft, fg: CC.blue },
  Rejected: { bg: CC.redSoft, fg: CC.red },
  rejected: { bg: CC.redSoft, fg: CC.red },
  banned: { bg: CC.redSoft, fg: CC.red },
  down: { bg: CC.redSoft, fg: CC.red },
  Expired: { bg: CC.redSoft, fg: CC.red },
  expired: { bg: CC.redSoft, fg: CC.red },
  Suspended: { bg: CC.amberSoft, fg: CC.amber },
  suspended: { bg: CC.amberSoft, fg: CC.amber },
  closed: { bg: '#F1F5F9', fg: CC.sub },
  dismissed: { bg: '#F1F5F9', fg: CC.sub },
  actioned: { bg: CC.tealSoft, fg: CC.teal },
  not_configured: { bg: '#F1F5F9', fg: CC.sub },
  mocked: { bg: CC.amberSoft, fg: CC.amber },
};
